name: Auto Generate and Commit

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto_generate_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Run code generation and commit
        run: |
          make generate
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Proto files regeneration"
          git push
